server:
    port: 8080

spring:
    application:
        name: Reactive DEMO API
    profiles:
        active: dev
        include:
    data:
        mongodb:
            host: localhost
            port: 27017
            authentication-database: admin
            database: test
            username: admin
            password: admin