spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            authentication-database: admin
            database: test
            username: admin
            password: admin